# path:
ckpt:
save_img_path:
pretrained_model_path: /path/to/VAE/checkpoint

# model config: 
model: Latte-S/2
num_frames: 16
image_size: 256 # choices=[256, 512]
frame_interval: 3
fixed_spatial: False
attention_bias: True
learn_sigma: False
extras: 2 # [1, 2] 1 unconditional generation, 2 class-conditional generation
model_stage: "bridge"
model_predict_type: "eps_psi"
num_classes: 101
condition_type: "concat_pre"
prior_encoder_type: "first_pixel"
sample_prior: "ground_truth"
nwarp_supervision_type:
nwarp_combine_lambda:

use_pretrained_nwarp: True
nwarp_config: configs/ucf101/ucf101_sample_nwarp.yaml
nwarp_ckpt: /path/to/neural/prior/model
nwarp_condition_type: "prior" # ["concat_only", "prior"]

dct_domain: False
use_quantile:
dct_quantile:
dct_coef_num:

# model speedup
use_compile: False
use_fp16: False

# sample config:
seed:
sample_method: 'bridge_sde'
num_sampling_steps: 1000
cfg_scale: 7.0 # 1.0 represents conditional only
run_time:
num_sample: 1
sample_names: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
negative_name: 101

# ddp sample config
per_proc_batch_size: 4
num_fvd_samples: 2048

# dataset for ground-truth prior
dataset: "ucf101"
data_path: "/path/to/UCF-101"

finetune_spatial_only:
finetune_snr_alignment:
mse_only: False